### ISSUE TITLE
Add CORS headers for OPTIONS request

### ISSUE THREAD

**Issue by Illyism** [SBP07/backend#2]
See https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests

And perhaps https://stackoverflow.com/questions/25152277/play-framework-2-3-cors-headers

**Comment by thomastoye** [comment]
Has to do with nginx, apparently, which doesn't seem to pass OPTIONS along. Will investigate more tomorrow. This looks promising: https://gist.github.com/pauloricardomg/7084524

**Comment by thomastoye** [comment]
Enabled CORS filter, but `nginx` sent `Access-Control-Allow-Origin` too, confusing the browser because that header was sent twice. I fixed this in the `sbp07backend` config. Please confirm it's working now, I don't have a lot of experience with CORS.

```
$ curl -i -H "google.com" -X GET http://backend.sbp07.il.ly/api/unprotected/tenant
HTTP/1.1 200 OK
Server: nginx/1.4.6 (Ubuntu)
Date: Thu, 19 Nov 2015 22:51:32 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 110
Connection: keep-alive
Access-Control-Allow-Origin: *
X-Made-By: SBP07

[{"id":"1bd3446a-8eb0-11e5-b09e-2fb0d306521e","canonicalName":"despeelberg","name":"Speelplein De Speelberg"}]%           
```

http://client.cors-api.appspot.com/client#?client_method=GET&client_credentials=false&server_url=http%3A%2F%2Fbackend.sbp07.il.ly%2Fapi%2Funprotected%2Ftenant&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote

**Comment by Illyism** [comment]
Works. Thank you.
